### PR TITLE
docker-compose support

### PR DESCRIPTION
**Pull request by lerra**
Created the PR for the issue https://github.com/converge/instapy-dashboard/issues/13 that I created

### CODE REVIEW

**Comment by converge** [comment]
that's amazing @lerra, thank you so much! this will help a lot of people!

I'll review and merge it this weekend.

**Comment by lerra** [comment]
@converge any update? :-)

**Comment by converge** [comment]
I had a look this weekend, but there is some issues like
```[1] Error: Please install sqlite3 package manually```
and it's creating empty folder inside the root folder, I also changed /root folder to /opt in the config files, I'll have time again this weekend, and I'll propose the changes, and ask for your thoughts.

**Comment by converge** [comment]
just created a new Docker image, could you test it ? https://github.com/converge/instapy-dashboard/pull/36

**Comment by lerra** [comment]
It works for me as long as I hardcode  - ${INSTAPY_FOLDER}:${INSTAPY_FOLDER} from the docker compose file to the folders where instapy is, but I guess that was the intent of it and not to have it dynamic ?

**Comment by converge** [comment]
Hey, I made a PR last week with a working image and Docker container, did you have some issue using my setup?

**Pull request closed without merging**
